name: Build and Publish DCS Dedicated Server (Pterodactyl) Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'   # e.g. v1.0.0
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fix line endings (if needed)
        run: sudo apt-get update && sudo apt-get install dos2unix -y && cd docker && dos2unix *.sh

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/dcs-dedi-serv-pterodactyl
          tags: |
            type=ref,event=branch,branch=main
            type=ref,event=tag
            type=raw,value=latest

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: ./docker
          file: ./docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
